---
title: "ESM 205 Assignment 5"
author: "Derek Nguyen"
date: "11/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(tidyverse)
library(effsize)
library(janitor)
library(tidyr)
library(tidyr)
library(kableExtra)
library(car)
library(ggbeeswarm)
```


```{r}
mack_creek_vert <- readr::read_csv("mack_creek_vertebrates.csv") %>% 
  clean_names()
```



```{r}
mack_creek_dite <- mack_creek_vert %>% 
  filter(species %in% "DITE") %>% 
  count(year, section)

mack_creek_dite_table <- mack_creek_dite %>% 
  pivot_wider(names_from = section, values_from = n)
```

```{r}
ggplot(data = mack_creek_dite, aes(x = year, y = n, fill = section)) +
  geom_col() +
  facet_wrap(~section)
```

```{r}
ggplot(data = mack_creek_dite, aes(x = year, y = n)) +
  geom_line(color = "green") +
  facet_wrap(~section) +
  scale_x_continuous(expand = c(0,0)) +
  theme_minimal() +
  labs(y = "Total Counts",
       title = "dd",
       x = NULL)
```









